### ISSUE TITLE
how do i start neo-one?

### ISSUE THREAD

**Issue by printerguykw** [neo-one-suite/neo-one#122]
followed the limited instructions and installed neo-one via npm and it installed fine on my ubuntu 16 system

When I try to start neo-one, I always get this error, Im not really sure how to start the service, and how to access this app, thanks

myuser@df23:~/dev$ neo-one 
/usr/lib/node_modules/@neo-one/cli/dist/index.js:364
  const initiateShutdown = async () => {
                                 ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@neo-one/cli/dist/bin/neo-one:6:9)
myuser@df23:~/dev$ sudo neo-one 
/usr/lib/node_modules/@neo-one/cli/dist/index.js:364
  const initiateShutdown = async () => {
                                 ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@neo-one/cli/dist/bin/neo-one:6:9)
myuser@df23:~/dev$ sudo neo-one 127.0.0.1
/usr/lib/node_modules/@neo-one/cli/dist/index.js:364
  const initiateShutdown = async () => {
                                 ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@neo-one/cli/dist/bin/neo-one:6:9)
myuser@df23:~/dev$

**Comment by dicarlo2** [comment]
Make sure you have node 8.9.0 or higher installed. With that said, neo-one isn't quite ready for use. We'll be updating the documentation and pushing some big updates in the next few weeks, stay tuned!

**Comment by dicarlo2** [comment]
Closing this out for organization, but know that we are working hard on improving neo-one - it's just not quite ready yet. We'll announce more broadly (reddit, twitter, etc.) once it's ready.
